//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Managers/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Movement"",
            ""id"": ""0a7bce25-ca92-423f-83cd-1107b135990f"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c83d4446-f412-4d71-97ef-530c688eb634"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ecb98de1-1785-4d0b-9224-94d8f0cac1b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RunStart"",
                    ""type"": ""Value"",
                    ""id"": ""607c1289-53bb-461b-8780-583b61645cd7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RunStop"",
                    ""type"": ""Button"",
                    ""id"": ""f0d94cec-1573-45b6-9271-2d776a472580"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""22d70a40-a0e3-4c1f-bf96-d120939851a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0132b81f-10aa-4a57-a17e-368cd75acf3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInv"",
                    ""type"": ""Button"",
                    ""id"": ""0fe6c5be-e51e-4f81-be06-06d34b6a6091"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpemMenu"",
                    ""type"": ""Button"",
                    ""id"": ""db7b94c1-34ce-47ad-9eba-209208cc3e0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenMap"",
                    ""type"": ""Button"",
                    ""id"": ""48421eaa-5bde-4ff4-88cd-1f03d4d47882"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenQuests"",
                    ""type"": ""Button"",
                    ""id"": ""0eb2530e-e3a2-46ad-b5c6-ff7cbeb75749"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenSkills"",
                    ""type"": ""Button"",
                    ""id"": ""0f11ece1-4698-4a05-805a-aea442b87f83"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenBestiary"",
                    ""type"": ""Button"",
                    ""id"": ""459788b6-8924-4380-b7d8-b5a72894f8ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenList"",
                    ""type"": ""Button"",
                    ""id"": ""69b26caa-1959-4551-b7b6-53d272da45c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""350df2a2-303b-44ed-8d28-e6bb76943e77"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CommonAttack"",
                    ""type"": ""Button"",
                    ""id"": ""88134ce4-f6bd-44a0-9e99-109ba88e126f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryAttack"",
                    ""type"": ""Button"",
                    ""id"": ""58efc6ae-a0fe-42ec-ac2f-460b01a70f89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability/Spell_1"",
                    ""type"": ""Button"",
                    ""id"": ""06414732-340f-46d7-98e7-3ef095aa1cd5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability/Spell_2"",
                    ""type"": ""Button"",
                    ""id"": ""3f324213-a570-4df6-b2e8-f8eb6cd481cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability/Spell_3"",
                    ""type"": ""Button"",
                    ""id"": ""61a47876-9b92-4ef9-a060-03fa6a6e6a0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability/Spell_4"",
                    ""type"": ""Button"",
                    ""id"": ""e96feec8-51d5-458d-82c2-dc37b94dc7bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WSAD"",
                    ""id"": ""2443b225-581d-4c4e-8bae-301a6b92d7d5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""098931a3-4b9d-4f02-ad07-6320cde3e835"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f84ebd20-a9a7-434a-9d89-82e192e29db5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""efb78af6-1748-4068-b209-7daa59ee5e3b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""13381b18-6b10-4fb4-bdb3-6181f7282387"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""92920a4c-610c-4620-b7b6-ce45cfdec8b4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""891c48d4-89ef-40f9-8d50-5a7de70be669"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""405e37e7-55a0-4552-a96c-b0dcd6186a4d"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""635e885a-fdab-41aa-96e3-f3b8b19b5067"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5529010f-e28f-4afa-a9be-299f6c16cd3d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6561f73c-f778-4ee6-b4b8-e6813e9824ad"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e636c29d-c7e4-4317-a604-1cb0df69e4f7"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInv"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87f6b4be-3a62-453e-91ed-14c4ad2a571f"",
                    ""path"": ""<XInputController>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInv"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1880ef5-2048-443d-aa7a-0800b35daacb"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpemMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b4b1fbf-bf2b-477c-b2a5-066971c5427c"",
                    ""path"": ""<XInputController>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpemMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""201310e4-6a64-43c0-aa71-2d8821ce259b"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RunStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfd0471e-c07a-413a-aa11-505eda25e87f"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RunStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98df818e-d43f-4774-adc6-746f650aed12"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RunStop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""463f3b25-f2cb-4216-a8a7-00ceb7f89b58"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RunStop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fdf4688-d9ab-4de7-94c3-8de88bdb0a4f"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c23337e8-ccde-46ec-886a-aa7115507407"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""123a971d-cfc9-4785-b83f-d54c14229e28"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Mouse&Keyboard"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4127b070-afe7-4443-b540-8722875db7dc"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e73584f6-dc3c-46d7-a579-af0fea7f8b7e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""365aed6a-fe30-445a-8e05-24317b504344"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02f481da-92dd-4793-a240-70b3886f8f50"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CommonAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44254a30-c3ec-4495-8f56-70f219eca429"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CommonAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02803685-40d8-41fc-80e8-5a7c2c44ceb3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43b7409c-937a-4799-835e-5ba7e866f4e9"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1566d1fa-fc23-4d3e-b811-9da3795e3ee3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability/Spell_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f62bd47-ee19-4768-b7d9-8ea657918256"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability/Spell_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e5f8c62-3305-46ff-b2bd-aa820b34bbbd"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability/Spell_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6cdb7c3e-08e7-4975-92d2-2b9618f2888c"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability/Spell_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ad97e91-e197-420f-bc2a-89500ccbea8f"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability/Spell_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""186f1f2d-5607-4992-b0a6-32c4953896bc"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability/Spell_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64584808-eee0-4db9-b444-472c0af2dbc0"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability/Spell_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e64d4037-3318-42b6-954c-28b8897b451a"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability/Spell_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57a12f5a-b089-4828-9252-d6fd3b8512ee"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89106133-7565-4c11-b20d-f613e344ee77"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenMap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""782af526-bfcc-4acf-8a8f-bec272087479"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Mouse&Keyboard"",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35cd951d-9554-4929-8828-5a1864d1d5c2"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenQuests"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66542a12-0202-42ed-98dc-3ff805927b92"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenSkills"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6d12781-40c9-45ab-9317-182a8ae4f4e1"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenBestiary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bb74958-5ac7-4775-b1d5-975d049fe709"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenList"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""5656afbd-bc8b-48b8-944f-2a5c10c3c476"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6a565a75-9261-4c52-81fd-2914367af6c0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""652ffa25-e6ff-4a8b-807a-823c71da3ace"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""PassThrough"",
                    ""id"": ""55b77431-20da-4101-aec2-a6a4819f25df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollUp"",
                    ""type"": ""Button"",
                    ""id"": ""4c607854-c50f-4578-b94d-f14a1e60545b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollDown"",
                    ""type"": ""Button"",
                    ""id"": ""ceb369a4-edbb-4766-ae47-f5d538794b2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Choose"",
                    ""type"": ""Button"",
                    ""id"": ""b694160d-dd6a-4628-bc28-da366cdd6f3e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkipDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""aefe7c1f-708f-40d2-a1bd-a631aec8a94c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeleteItem"",
                    ""type"": ""Button"",
                    ""id"": ""59a8515a-4ea8-419a-921b-70b01ff15992"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Button"",
                    ""id"": ""680423cd-c7c1-45ef-91dc-2f2b33918fc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""c938af07-52bc-4ba9-ba19-b3a7faa52d21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipItem"",
                    ""type"": ""Button"",
                    ""id"": ""0d34c89a-72c5-455c-8482-64e67f4295de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a59bc74f-3fd8-460c-8bf9-92049104b30c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f3c2f72-1893-4e87-b70d-c88385515fec"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05e59c3b-dd3e-45b7-998c-1c7c3738fe2b"",
                    ""path"": ""<VirtualMouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e1c8903-6df7-4490-a971-1c200f1ae720"",
                    ""path"": ""<Keyboard>/minus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a64417f-2a12-4863-848d-26feffa976db"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eaf4ae46-b23b-4c70-9964-43cc8a46560c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6e1fcdd-1942-4193-bb83-1a9e4a7b7490"",
                    ""path"": ""<VirtualMouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71788cf6-488b-4438-a068-7167f0b69d56"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44bd8664-058a-48d0-9418-b9c50b396a69"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse&Keyboard"",
                    ""action"": ""Choose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d21a5cc-1ddd-44e4-9a2d-abf9a32cb138"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""883957e6-7e0e-4c6a-9a4e-7b8fde5389c7"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Choose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0abc5bc1-2908-489f-9768-1f2469516f57"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SkipDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99a193a5-584f-4bcb-a701-a5becd9ebc03"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeleteItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6dd185b2-7c08-4c78-a5d7-1e887473cd8e"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeleteItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81e7f677-6ea6-457b-851f-bfe4108e0367"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f20bee9d-4a95-4d2f-9501-73e74bf11302"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a25e9a96-7ef8-4543-bf99-4f81cf0183a6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7327c090-3a8a-46b2-a310-39aca2aa996e"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d49b1681-ae4a-45fc-939e-90f4f12e9322"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5530c8fc-4341-4cb1-aa01-53861d52bb27"",
                    ""path"": ""<Keyboard>/equals"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff39a28a-9010-401d-8952-b022524874b7"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<VirtualMouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Mouse&Keyboard"",
            ""bindingGroup"": ""Mouse&Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Movement
        m_Movement = asset.FindActionMap("Movement", throwIfNotFound: true);
        m_Movement_Move = m_Movement.FindAction("Move", throwIfNotFound: true);
        m_Movement_Interact = m_Movement.FindAction("Interact", throwIfNotFound: true);
        m_Movement_RunStart = m_Movement.FindAction("RunStart", throwIfNotFound: true);
        m_Movement_RunStop = m_Movement.FindAction("RunStop", throwIfNotFound: true);
        m_Movement_Roll = m_Movement.FindAction("Roll", throwIfNotFound: true);
        m_Movement_Dodge = m_Movement.FindAction("Dodge", throwIfNotFound: true);
        m_Movement_OpenInv = m_Movement.FindAction("OpenInv", throwIfNotFound: true);
        m_Movement_OpemMenu = m_Movement.FindAction("OpemMenu", throwIfNotFound: true);
        m_Movement_OpenMap = m_Movement.FindAction("OpenMap", throwIfNotFound: true);
        m_Movement_OpenQuests = m_Movement.FindAction("OpenQuests", throwIfNotFound: true);
        m_Movement_OpenSkills = m_Movement.FindAction("OpenSkills", throwIfNotFound: true);
        m_Movement_OpenBestiary = m_Movement.FindAction("OpenBestiary", throwIfNotFound: true);
        m_Movement_OpenList = m_Movement.FindAction("OpenList", throwIfNotFound: true);
        m_Movement_Block = m_Movement.FindAction("Block", throwIfNotFound: true);
        m_Movement_CommonAttack = m_Movement.FindAction("CommonAttack", throwIfNotFound: true);
        m_Movement_SecondaryAttack = m_Movement.FindAction("SecondaryAttack", throwIfNotFound: true);
        m_Movement_AbilitySpell_1 = m_Movement.FindAction("Ability/Spell_1", throwIfNotFound: true);
        m_Movement_AbilitySpell_2 = m_Movement.FindAction("Ability/Spell_2", throwIfNotFound: true);
        m_Movement_AbilitySpell_3 = m_Movement.FindAction("Ability/Spell_3", throwIfNotFound: true);
        m_Movement_AbilitySpell_4 = m_Movement.FindAction("Ability/Spell_4", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
        m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
        m_UI_Select = m_UI.FindAction("Select", throwIfNotFound: true);
        m_UI_ScrollUp = m_UI.FindAction("ScrollUp", throwIfNotFound: true);
        m_UI_ScrollDown = m_UI.FindAction("ScrollDown", throwIfNotFound: true);
        m_UI_Choose = m_UI.FindAction("Choose", throwIfNotFound: true);
        m_UI_SkipDialogue = m_UI.FindAction("SkipDialogue", throwIfNotFound: true);
        m_UI_DeleteItem = m_UI.FindAction("DeleteItem", throwIfNotFound: true);
        m_UI_UseItem = m_UI.FindAction("UseItem", throwIfNotFound: true);
        m_UI_Confirm = m_UI.FindAction("Confirm", throwIfNotFound: true);
        m_UI_EquipItem = m_UI.FindAction("EquipItem", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movement
    private readonly InputActionMap m_Movement;
    private IMovementActions m_MovementActionsCallbackInterface;
    private readonly InputAction m_Movement_Move;
    private readonly InputAction m_Movement_Interact;
    private readonly InputAction m_Movement_RunStart;
    private readonly InputAction m_Movement_RunStop;
    private readonly InputAction m_Movement_Roll;
    private readonly InputAction m_Movement_Dodge;
    private readonly InputAction m_Movement_OpenInv;
    private readonly InputAction m_Movement_OpemMenu;
    private readonly InputAction m_Movement_OpenMap;
    private readonly InputAction m_Movement_OpenQuests;
    private readonly InputAction m_Movement_OpenSkills;
    private readonly InputAction m_Movement_OpenBestiary;
    private readonly InputAction m_Movement_OpenList;
    private readonly InputAction m_Movement_Block;
    private readonly InputAction m_Movement_CommonAttack;
    private readonly InputAction m_Movement_SecondaryAttack;
    private readonly InputAction m_Movement_AbilitySpell_1;
    private readonly InputAction m_Movement_AbilitySpell_2;
    private readonly InputAction m_Movement_AbilitySpell_3;
    private readonly InputAction m_Movement_AbilitySpell_4;
    public struct MovementActions
    {
        private @PlayerControls m_Wrapper;
        public MovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Movement_Move;
        public InputAction @Interact => m_Wrapper.m_Movement_Interact;
        public InputAction @RunStart => m_Wrapper.m_Movement_RunStart;
        public InputAction @RunStop => m_Wrapper.m_Movement_RunStop;
        public InputAction @Roll => m_Wrapper.m_Movement_Roll;
        public InputAction @Dodge => m_Wrapper.m_Movement_Dodge;
        public InputAction @OpenInv => m_Wrapper.m_Movement_OpenInv;
        public InputAction @OpemMenu => m_Wrapper.m_Movement_OpemMenu;
        public InputAction @OpenMap => m_Wrapper.m_Movement_OpenMap;
        public InputAction @OpenQuests => m_Wrapper.m_Movement_OpenQuests;
        public InputAction @OpenSkills => m_Wrapper.m_Movement_OpenSkills;
        public InputAction @OpenBestiary => m_Wrapper.m_Movement_OpenBestiary;
        public InputAction @OpenList => m_Wrapper.m_Movement_OpenList;
        public InputAction @Block => m_Wrapper.m_Movement_Block;
        public InputAction @CommonAttack => m_Wrapper.m_Movement_CommonAttack;
        public InputAction @SecondaryAttack => m_Wrapper.m_Movement_SecondaryAttack;
        public InputAction @AbilitySpell_1 => m_Wrapper.m_Movement_AbilitySpell_1;
        public InputAction @AbilitySpell_2 => m_Wrapper.m_Movement_AbilitySpell_2;
        public InputAction @AbilitySpell_3 => m_Wrapper.m_Movement_AbilitySpell_3;
        public InputAction @AbilitySpell_4 => m_Wrapper.m_Movement_AbilitySpell_4;
        public InputActionMap Get() { return m_Wrapper.m_Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
        public void SetCallbacks(IMovementActions instance)
        {
            if (m_Wrapper.m_MovementActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnMove;
                @Interact.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnInteract;
                @RunStart.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnRunStart;
                @RunStart.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnRunStart;
                @RunStart.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnRunStart;
                @RunStop.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnRunStop;
                @RunStop.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnRunStop;
                @RunStop.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnRunStop;
                @Roll.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnRoll;
                @Roll.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnRoll;
                @Roll.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnRoll;
                @Dodge.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnDodge;
                @Dodge.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnDodge;
                @Dodge.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnDodge;
                @OpenInv.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenInv;
                @OpenInv.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenInv;
                @OpenInv.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenInv;
                @OpemMenu.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpemMenu;
                @OpemMenu.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpemMenu;
                @OpemMenu.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpemMenu;
                @OpenMap.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenMap;
                @OpenMap.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenMap;
                @OpenMap.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenMap;
                @OpenQuests.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenQuests;
                @OpenQuests.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenQuests;
                @OpenQuests.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenQuests;
                @OpenSkills.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenSkills;
                @OpenSkills.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenSkills;
                @OpenSkills.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenSkills;
                @OpenBestiary.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenBestiary;
                @OpenBestiary.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenBestiary;
                @OpenBestiary.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenBestiary;
                @OpenList.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenList;
                @OpenList.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenList;
                @OpenList.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnOpenList;
                @Block.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnBlock;
                @Block.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnBlock;
                @Block.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnBlock;
                @CommonAttack.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnCommonAttack;
                @CommonAttack.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnCommonAttack;
                @CommonAttack.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnCommonAttack;
                @SecondaryAttack.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnSecondaryAttack;
                @SecondaryAttack.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnSecondaryAttack;
                @SecondaryAttack.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnSecondaryAttack;
                @AbilitySpell_1.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_1;
                @AbilitySpell_1.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_1;
                @AbilitySpell_1.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_1;
                @AbilitySpell_2.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_2;
                @AbilitySpell_2.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_2;
                @AbilitySpell_2.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_2;
                @AbilitySpell_3.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_3;
                @AbilitySpell_3.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_3;
                @AbilitySpell_3.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_3;
                @AbilitySpell_4.started -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_4;
                @AbilitySpell_4.performed -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_4;
                @AbilitySpell_4.canceled -= m_Wrapper.m_MovementActionsCallbackInterface.OnAbilitySpell_4;
            }
            m_Wrapper.m_MovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @RunStart.started += instance.OnRunStart;
                @RunStart.performed += instance.OnRunStart;
                @RunStart.canceled += instance.OnRunStart;
                @RunStop.started += instance.OnRunStop;
                @RunStop.performed += instance.OnRunStop;
                @RunStop.canceled += instance.OnRunStop;
                @Roll.started += instance.OnRoll;
                @Roll.performed += instance.OnRoll;
                @Roll.canceled += instance.OnRoll;
                @Dodge.started += instance.OnDodge;
                @Dodge.performed += instance.OnDodge;
                @Dodge.canceled += instance.OnDodge;
                @OpenInv.started += instance.OnOpenInv;
                @OpenInv.performed += instance.OnOpenInv;
                @OpenInv.canceled += instance.OnOpenInv;
                @OpemMenu.started += instance.OnOpemMenu;
                @OpemMenu.performed += instance.OnOpemMenu;
                @OpemMenu.canceled += instance.OnOpemMenu;
                @OpenMap.started += instance.OnOpenMap;
                @OpenMap.performed += instance.OnOpenMap;
                @OpenMap.canceled += instance.OnOpenMap;
                @OpenQuests.started += instance.OnOpenQuests;
                @OpenQuests.performed += instance.OnOpenQuests;
                @OpenQuests.canceled += instance.OnOpenQuests;
                @OpenSkills.started += instance.OnOpenSkills;
                @OpenSkills.performed += instance.OnOpenSkills;
                @OpenSkills.canceled += instance.OnOpenSkills;
                @OpenBestiary.started += instance.OnOpenBestiary;
                @OpenBestiary.performed += instance.OnOpenBestiary;
                @OpenBestiary.canceled += instance.OnOpenBestiary;
                @OpenList.started += instance.OnOpenList;
                @OpenList.performed += instance.OnOpenList;
                @OpenList.canceled += instance.OnOpenList;
                @Block.started += instance.OnBlock;
                @Block.performed += instance.OnBlock;
                @Block.canceled += instance.OnBlock;
                @CommonAttack.started += instance.OnCommonAttack;
                @CommonAttack.performed += instance.OnCommonAttack;
                @CommonAttack.canceled += instance.OnCommonAttack;
                @SecondaryAttack.started += instance.OnSecondaryAttack;
                @SecondaryAttack.performed += instance.OnSecondaryAttack;
                @SecondaryAttack.canceled += instance.OnSecondaryAttack;
                @AbilitySpell_1.started += instance.OnAbilitySpell_1;
                @AbilitySpell_1.performed += instance.OnAbilitySpell_1;
                @AbilitySpell_1.canceled += instance.OnAbilitySpell_1;
                @AbilitySpell_2.started += instance.OnAbilitySpell_2;
                @AbilitySpell_2.performed += instance.OnAbilitySpell_2;
                @AbilitySpell_2.canceled += instance.OnAbilitySpell_2;
                @AbilitySpell_3.started += instance.OnAbilitySpell_3;
                @AbilitySpell_3.performed += instance.OnAbilitySpell_3;
                @AbilitySpell_3.canceled += instance.OnAbilitySpell_3;
                @AbilitySpell_4.started += instance.OnAbilitySpell_4;
                @AbilitySpell_4.performed += instance.OnAbilitySpell_4;
                @AbilitySpell_4.canceled += instance.OnAbilitySpell_4;
            }
        }
    }
    public MovementActions @Movement => new MovementActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Navigate;
    private readonly InputAction m_UI_Point;
    private readonly InputAction m_UI_Select;
    private readonly InputAction m_UI_ScrollUp;
    private readonly InputAction m_UI_ScrollDown;
    private readonly InputAction m_UI_Choose;
    private readonly InputAction m_UI_SkipDialogue;
    private readonly InputAction m_UI_DeleteItem;
    private readonly InputAction m_UI_UseItem;
    private readonly InputAction m_UI_Confirm;
    private readonly InputAction m_UI_EquipItem;
    public struct UIActions
    {
        private @PlayerControls m_Wrapper;
        public UIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
        public InputAction @Point => m_Wrapper.m_UI_Point;
        public InputAction @Select => m_Wrapper.m_UI_Select;
        public InputAction @ScrollUp => m_Wrapper.m_UI_ScrollUp;
        public InputAction @ScrollDown => m_Wrapper.m_UI_ScrollDown;
        public InputAction @Choose => m_Wrapper.m_UI_Choose;
        public InputAction @SkipDialogue => m_Wrapper.m_UI_SkipDialogue;
        public InputAction @DeleteItem => m_Wrapper.m_UI_DeleteItem;
        public InputAction @UseItem => m_Wrapper.m_UI_UseItem;
        public InputAction @Confirm => m_Wrapper.m_UI_Confirm;
        public InputAction @EquipItem => m_Wrapper.m_UI_EquipItem;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Navigate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Select.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSelect;
                @ScrollUp.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollUp;
                @ScrollUp.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollUp;
                @ScrollUp.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollUp;
                @ScrollDown.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollDown;
                @ScrollDown.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollDown;
                @ScrollDown.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollDown;
                @Choose.started -= m_Wrapper.m_UIActionsCallbackInterface.OnChoose;
                @Choose.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnChoose;
                @Choose.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnChoose;
                @SkipDialogue.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSkipDialogue;
                @SkipDialogue.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSkipDialogue;
                @SkipDialogue.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSkipDialogue;
                @DeleteItem.started -= m_Wrapper.m_UIActionsCallbackInterface.OnDeleteItem;
                @DeleteItem.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnDeleteItem;
                @DeleteItem.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnDeleteItem;
                @UseItem.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUseItem;
                @UseItem.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUseItem;
                @UseItem.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUseItem;
                @Confirm.started -= m_Wrapper.m_UIActionsCallbackInterface.OnConfirm;
                @Confirm.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnConfirm;
                @Confirm.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnConfirm;
                @EquipItem.started -= m_Wrapper.m_UIActionsCallbackInterface.OnEquipItem;
                @EquipItem.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnEquipItem;
                @EquipItem.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnEquipItem;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @ScrollUp.started += instance.OnScrollUp;
                @ScrollUp.performed += instance.OnScrollUp;
                @ScrollUp.canceled += instance.OnScrollUp;
                @ScrollDown.started += instance.OnScrollDown;
                @ScrollDown.performed += instance.OnScrollDown;
                @ScrollDown.canceled += instance.OnScrollDown;
                @Choose.started += instance.OnChoose;
                @Choose.performed += instance.OnChoose;
                @Choose.canceled += instance.OnChoose;
                @SkipDialogue.started += instance.OnSkipDialogue;
                @SkipDialogue.performed += instance.OnSkipDialogue;
                @SkipDialogue.canceled += instance.OnSkipDialogue;
                @DeleteItem.started += instance.OnDeleteItem;
                @DeleteItem.performed += instance.OnDeleteItem;
                @DeleteItem.canceled += instance.OnDeleteItem;
                @UseItem.started += instance.OnUseItem;
                @UseItem.performed += instance.OnUseItem;
                @UseItem.canceled += instance.OnUseItem;
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
                @EquipItem.started += instance.OnEquipItem;
                @EquipItem.performed += instance.OnEquipItem;
                @EquipItem.canceled += instance.OnEquipItem;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_MouseKeyboardSchemeIndex = -1;
    public InputControlScheme MouseKeyboardScheme
    {
        get
        {
            if (m_MouseKeyboardSchemeIndex == -1) m_MouseKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse&Keyboard");
            return asset.controlSchemes[m_MouseKeyboardSchemeIndex];
        }
    }
    public interface IMovementActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnRunStart(InputAction.CallbackContext context);
        void OnRunStop(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnDodge(InputAction.CallbackContext context);
        void OnOpenInv(InputAction.CallbackContext context);
        void OnOpemMenu(InputAction.CallbackContext context);
        void OnOpenMap(InputAction.CallbackContext context);
        void OnOpenQuests(InputAction.CallbackContext context);
        void OnOpenSkills(InputAction.CallbackContext context);
        void OnOpenBestiary(InputAction.CallbackContext context);
        void OnOpenList(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnCommonAttack(InputAction.CallbackContext context);
        void OnSecondaryAttack(InputAction.CallbackContext context);
        void OnAbilitySpell_1(InputAction.CallbackContext context);
        void OnAbilitySpell_2(InputAction.CallbackContext context);
        void OnAbilitySpell_3(InputAction.CallbackContext context);
        void OnAbilitySpell_4(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnScrollUp(InputAction.CallbackContext context);
        void OnScrollDown(InputAction.CallbackContext context);
        void OnChoose(InputAction.CallbackContext context);
        void OnSkipDialogue(InputAction.CallbackContext context);
        void OnDeleteItem(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
        void OnConfirm(InputAction.CallbackContext context);
        void OnEquipItem(InputAction.CallbackContext context);
    }
}
